import 'package:flutter_application_1/models/cars.dart';


final List<Service> SparkleWashServices = [
  Service(id: '1', name: 'Exterior Car Washing', description: 'Thorough cleaning of the vehicle exterior.', price: 1500.0),
  Service(id: '2', name: 'Interior Vacuuming & Cleaning', description: 'Vacuum and clean interior surfaces.', price: 2500.0),
  Service(id: '3', name: 'Engine Cleaning', description: 'Degrease and clean engine bay.', price: 3500.0),
  Service(id: '4', name: 'Undercarriage Cleaning', description: 'Clean vehicle undercarriage.', price: 3000.0),
  Service(id: '5', name: 'Car Detailing', description: 'Complete interior and exterior detailing.', price: 1200.0),
 Service(id: '6', name: 'Air Purge (Dash & Console)', description: 'Clean and freshen air vents and dash.', price: 2000.0),
  Service(id: '7', name: 'Carpet Shampoo', description: 'Deep clean carpets and upholstery.', price: 3500.0),
  Service(id: '8', name: 'Seat & Upholstery Shampoo', description: 'Clean seats and upholstery fabrics.', price: 3500.0),
  Service(id: '9', name: 'Interior Detail', description: 'Detailed cleaning and conditioning of interior.', price: 0180.0),
  Service(id: '10', name: 'Full Detail', description: 'Complete interior and exterior detail.', price: 2500.0),
  Service(id: '11', name: 'Mobile Car Wash', description: 'Car wash service at your location.', price: 1050.0),
  Service(id: '12', name: '24-Hour Car Wash', description: 'Car wash available 24/7.', price: 2000.0),
 Service(id: '14', name: 'Car Detailing', description: 'Complete interior and exterior detailing.', price: 1200.0),
];
final List<Service> CleanRide = [
  Service(id: '1', name: 'Exterior Car Washing', description: 'Thorough cleaning of the vehicle exterior.', price: 1520.0),
  Service(id: '2', name: 'Interior Vacuuming & Cleaning', description: 'Vacuum and clean interior surfaces.', price: 5500.0),
  Service(id: '3', name: 'Engine Cleaning', description: 'Degrease and clean engine bay.', price: 4500.0),
  Service(id: '4', name: 'Undercarriage Cleaning', description: 'Clean vehicle undercarriage.', price: 5000.0),
  Service(id: '5', name: 'Car Detailing', description: 'Complete interior and exterior detailing.', price: 1200.0),
 Service(id: '6', name: 'Air Purge (Dash & Console)', description: 'Clean and freshen air vents and dash.', price: 2000.0),
  Service(id: '7', name: 'Carpet Shampoo', description: 'Deep clean carpets and upholstery.', price: 3500.0),
  Service(id: '8', name: 'Seat & Upholstery Shampoo', description: 'Clean seats and upholstery fabrics.', price: 3505.0),
  Service(id: '9', name: 'Interior Detail', description: 'Detailed cleaning and conditioning of interior.', price: 1180.0),
  Service(id: '10', name: 'Full Detail', description: 'Complete interior and exterior detail.', price: 2550.0),
  Service(id: '11', name: 'Mobile Car Wash', description: 'Car wash service at your location.', price: 3050.0),
  Service(id: '12', name: '24-Hour Car Wash', description: 'Car wash available 24/7.', price: 4000.0),
 Service(id: '14', name: 'Car Detailing', description: 'Complete interior and exterior detailing.', price: 3200.0),
];
final List<Service> ExtremeCleanAnanasMall = [
  Service(id: '1', name: 'Exterior Car Washing', description: 'Thorough cleaning of the vehicle exterior.', price: 1600.0),
  Service(id: '2', name: 'Interior Vacuuming & Cleaning', description: 'Vacuum and clean interior surfaces.', price: 6500.0),
  Service(id: '3', name: 'Engine Cleaning', description: 'Degrease and clean engine bay.', price: 3600.0),
  Service(id: '4', name: 'Undercarriage Cleaning', description: 'Clean vehicle undercarriage.', price: 3500.0),
  Service(id: '5', name: 'Car Detailing', description: 'Complete interior and exterior detailing.', price: 1600.0),
 Service(id: '6', name: 'Air Purge (Dash & Console)', description: 'Clean and freshen air vents and dash.', price: 2500.0),
  Service(id: '7', name: 'Carpet Shampoo', description: 'Deep clean carpets and upholstery.', price: 3560.0),
  Service(id: '8', name: 'Seat & Upholstery Shampoo', description: 'Clean seats and upholstery fabrics.', price: 3570.0),
  Service(id: '9', name: 'Interior Detail', description: 'Detailed cleaning and conditioning of interior.', price: 1180.0),
  Service(id: '10', name: 'Full Detail', description: 'Complete interior and exterior detail.', price: 2560.0),
  Service(id: '11', name: 'Mobile Car Wash', description: 'Car wash service at your location.', price: 1060.0),
  Service(id: '12', name: '24-Hour Car Wash', description: 'Car wash available 24/7.', price: 2006.0),
 Service(id: '14', name: 'Car Detailing', description: 'Complete interior and exterior detailing.', price: 1500.0),
];
final List<Service> AshworthCarWash = [
  Service(id: '1', name: 'Exterior Car Washing', description: 'Thorough cleaning of the vehicle exterior.', price: 1700.0),
  Service(id: '2', name: 'Interior Vacuuming & Cleaning', description: 'Vacuum and clean interior surfaces.', price: 5500.0),
  Service(id: '3', name: 'Engine Cleaning', description: 'Degrease and clean engine bay.', price: 3500.0),
  Service(id: '4', name: 'Undercarriage Cleaning', description: 'Clean vehicle undercarriage.', price: 3500.0),
  Service(id: '5', name: 'Car Detailing', description: 'Complete interior and exterior detailing.', price: 1200.0),
 Service(id: '6', name: 'Air Purge (Dash & Console)', description: 'Clean and freshen air vents and dash.', price: 6000.0),
  Service(id: '7', name: 'Carpet Shampoo', description: 'Deep clean carpets and upholstery.', price: 3500.0),
  Service(id: '8', name: 'Seat & Upholstery Shampoo', description: 'Clean seats and upholstery fabrics.', price: 3600.0),
  Service(id: '9', name: 'Interior Detail', description: 'Detailed cleaning and conditioning of interior.', price: 2180.0),
  Service(id: '10', name: 'Full Detail', description: 'Complete interior and exterior detail.', price: 2570.0),
  Service(id: '11', name: 'Mobile Car Wash', description: 'Car wash service at your location.', price: 2050.0),
  Service(id: '12', name: '24-Hour Car Wash', description: 'Car wash available 24/7.', price: 2300.0),
 Service(id: '14', name: 'Car Detailing', description: 'Complete interior and exterior detailing.', price: 1260.0),
];
final List<Service> AutoSparkleCarWash = [
  Service(id: '1', name: 'Exterior Car Washing', description: 'Thorough cleaning of the vehicle exterior.', price: 1600.0),
  Service(id: '2', name: 'Interior Vacuuming & Cleaning', description: 'Vacuum and clean interior surfaces.', price: 2600.0),
  Service(id: '3', name: 'Engine Cleaning', description: 'Degrease and clean engine bay.', price: 3500.0),
  Service(id: '4', name: 'Undercarriage Cleaning', description: 'Clean vehicle undercarriage.', price: 3000.0),
  Service(id: '5', name: 'Car Detailing', description: 'Complete interior and exterior detailing.', price: 1200.0),
 Service(id: '6', name: 'Air Purge (Dash & Console)', description: 'Clean and freshen air vents and dash.', price: 2000.0),
  Service(id: '7', name: 'Carpet Shampoo', description: 'Deep clean carpets and upholstery.', price: 3500.0),
  Service(id: '8', name: 'Seat & Upholstery Shampoo', description: 'Clean seats and upholstery fabrics.', price: 3500.0),
  Service(id: '9', name: 'Interior Detail', description: 'Detailed cleaning and conditioning of interior.', price: 6180.0),
  Service(id: '10', name: 'Full Detail', description: 'Complete interior and exterior detail.', price: 2500.0),
  Service(id: '11', name: 'Mobile Car Wash', description: 'Car wash service at your location.', price: 1650.0),
  Service(id: '12', name: '24-Hour Car Wash', description: 'Car wash available 24/7.', price: 2000.0),
 Service(id: '14', name: 'Car Detailing', description: 'Complete interior and exterior detailing.', price: 1200.0),
];

final List<Service>  TheRokCarwash = [
  Service(id: '1', name: 'Exterior Car Washing', description: 'Thorough cleaning of the vehicle exterior.', price: 1000.0),
  Service(id: '2', name: 'Interior Vacuuming & Cleaning', description: 'Vacuum and clean interior surfaces.', price: 2500.0),
  Service(id: '3', name: 'Engine Cleaning', description: 'Degrease and clean engine bay.', price: 3000.0),
  Service(id: '4', name: 'Undercarriage Cleaning', description: 'Clean vehicle undercarriage.', price: 3000.0),
  Service(id: '5', name: 'Car Detailing', description: 'Complete interior and exterior detailing.', price: 1200.0),
 Service(id: '6', name: 'Air Purge (Dash & Console)', description: 'Clean and freshen air vents and dash.', price: 2500.0),
  Service(id: '7', name: 'Carpet Shampoo', description: 'Deep clean carpets and upholstery.', price: 3500.0),
  Service(id: '8', name: 'Seat & Upholstery Shampoo', description: 'Clean seats and upholstery fabrics.', price: 3500.0),
  Service(id: '9', name: 'Interior Detail', description: 'Detailed cleaning and conditioning of interior.', price: 0180.0),
  Service(id: '10', name: 'Full Detail', description: 'Complete interior and exterior detail.', price: 2500.0),
  Service(id: '11', name: 'Mobile Car Wash', description: 'Car wash service at your location.', price: 1050.0),
  Service(id: '12', name: '24-Hour Car Wash', description: 'Car wash available 24/7.', price: 2000.0),
 Service(id: '14', name: 'Car Detailing', description: 'Complete interior and exterior detailing.', price: 1200.0),
];

final List<Service>  WambuguCarWashCentre = [
  Service(id: '1', name: 'Exterior Car Washing', description: 'Thorough cleaning of the vehicle exterior.', price: 1900.0),
  Service(id: '2', name: 'Interior Vacuuming & Cleaning', description: 'Vacuum and clean interior surfaces.', price: 2500.0),
  Service(id: '3', name: 'Engine Cleaning', description: 'Degrease and clean engine bay.', price: 3500.0),
  Service(id: '4', name: 'Undercarriage Cleaning', description: 'Clean vehicle undercarriage.', price: 3000.0),
  Service(id: '5', name: 'Car Detailing', description: 'Complete interior and exterior detailing.', price: 1200.0),
 Service(id: '6', name: 'Air Purge (Dash & Console)', description: 'Clean and freshen air vents and dash.', price: 2000.0),
  Service(id: '7', name: 'Carpet Shampoo', description: 'Deep clean carpets and upholstery.', price: 3500.0),
  Service(id: '8', name: 'Seat & Upholstery Shampoo', description: 'Clean seats and upholstery fabrics.', price: 3590.0),
  Service(id: '9', name: 'Interior Detail', description: 'Detailed cleaning and conditioning of interior.', price: 0180.0),
  Service(id: '10', name: 'Full Detail', description: 'Complete interior and exterior detail.', price: 2500.0),
  Service(id: '11', name: 'Mobile Car Wash', description: 'Car wash service at your location.', price: 1050.0),
  Service(id: '12', name: '24-Hour Car Wash', description: 'Car wash available 24/7.', price: 2000.0),
 Service(id: '14', name: 'Car Detailing', description: 'Complete interior and exterior detailing.', price: 1200.0),
];

final List<Service> TheAccacianCarWash = [
  Service(id: '1', name: 'Exterior Car Washing', description: 'Thorough cleaning of the vehicle exterior.', price: 1600.0),
  Service(id: '2', name: 'Interior Vacuuming & Cleaning', description: 'Vacuum and clean interior surfaces.', price: 2500.0),
  Service(id: '3', name: 'Engine Cleaning', description: 'Degrease and clean engine bay.', price: 3500.0),
  Service(id: '4', name: 'Undercarriage Cleaning', description: 'Clean vehicle undercarriage.', price: 3000.0),
  Service(id: '5', name: 'Car Detailing', description: 'Complete interior and exterior detailing.', price: 1200.0),
 Service(id: '6', name: 'Air Purge (Dash & Console)', description: 'Clean and freshen air vents and dash.', price: 2050.0),
  Service(id: '7', name: 'Carpet Shampoo', description: 'Deep clean carpets and upholstery.', price: 3500.0),
  Service(id: '8', name: 'Seat & Upholstery Shampoo', description: 'Clean seats and upholstery fabrics.', price: 2500.0),
  Service(id: '9', name: 'Interior Detail', description: 'Detailed cleaning and conditioning of interior.', price: 0180.0),
  Service(id: '10', name: 'Full Detail', description: 'Complete interior and exterior detail.', price: 2500.0),
  Service(id: '11', name: 'Mobile Car Wash', description: 'Car wash service at your location.', price: 1050.0),
  Service(id: '12', name: '24-Hour Car Wash', description: 'Car wash available 24/7.', price: 2000.0),
 Service(id: '14', name: 'Car Detailing', description: 'Complete interior and exterior detailing.', price: 1200.0),
];
final List<Service> HappyVantageCarWash = [
  Service(id: '1', name: 'Exterior Car Washing', description: 'Thorough cleaning of the vehicle exterior.', price: 2500.0),
  Service(id: '2', name: 'Interior Vacuuming & Cleaning', description: 'Vacuum and clean interior surfaces.', price: 2500.0),
  Service(id: '3', name: 'Engine Cleaning', description: 'Degrease and clean engine bay.', price: 3500.0),
  Service(id: '4', name: 'Undercarriage Cleaning', description: 'Clean vehicle undercarriage.', price: 3000.0),
  Service(id: '5', name: 'Car Detailing', description: 'Complete interior and exterior detailing.', price: 1200.0),
 Service(id: '6', name: 'Air Purge (Dash & Console)', description: 'Clean and freshen air vents and dash.', price: 2050.0),
  Service(id: '7', name: 'Carpet Shampoo', description: 'Deep clean carpets and upholstery.', price: 3500.0),
  Service(id: '8', name: 'Seat & Upholstery Shampoo', description: 'Clean seats and upholstery fabrics.', price: 5500.0),
  Service(id: '9', name: 'Interior Detail', description: 'Detailed cleaning and conditioning of interior.', price: 0180.0),
  Service(id: '10', name: 'Full Detail', description: 'Complete interior and exterior detail.', price: 2500.0),
  Service(id: '11', name: 'Mobile Car Wash', description: 'Car wash service at your location.', price: 1050.0),
  Service(id: '12', name: '24-Hour Car Wash', description: 'Car wash available 24/7.', price: 2000.0),
 Service(id: '14', name: 'Car Detailing', description: 'Complete interior and exterior detailing.', price: 1200.0),
];
final List<Service> SafiCarWash = [
  Service(id: '1', name: 'Exterior Car Washing', description: 'Thorough cleaning of the vehicle exterior.', price: 2500.0),
  Service(id: '2', name: 'Interior Vacuuming & Cleaning', description: 'Vacuum and clean interior surfaces.', price: 2500.0),
  Service(id: '3', name: 'Engine Cleaning', description: 'Degrease and clean engine bay.', price: 3500.0),
  Service(id: '4', name: 'Undercarriage Cleaning', description: 'Clean vehicle undercarriage.', price: 3000.0),
  Service(id: '5', name: 'Car Detailing', description: 'Complete interior and exterior detailing.', price: 1200.0),
 Service(id: '6', name: 'Air Purge (Dash & Console)', description: 'Clean and freshen air vents and dash.', price: 2000.0),
  Service(id: '7', name: 'Carpet Shampoo', description: 'Deep clean carpets and upholstery.', price: 3500.0),
  Service(id: '8', name: 'Seat & Upholstery Shampoo', description: 'Clean seats and upholstery fabrics.', price: 3500.0),
  Service(id: '9', name: 'Interior Detail', description: 'Detailed cleaning and conditioning of interior.', price: 0180.0),
  Service(id: '10', name: 'Full Detail', description: 'Complete interior and exterior detail.', price: 2600.0),
  Service(id: '11', name: 'Mobile Car Wash', description: 'Car wash service at your location.', price: 1050.0),
  Service(id: '12', name: '24-Hour Car Wash', description: 'Car wash available 24/7.', price: 2000.0),
 Service(id: '14', name: 'Car Detailing', description: 'Complete interior and exterior detailing.', price: 1200.0),
];


final List<CarWash> carWashes = [
  CarWash(
    id: '1',
    name: 'Sparkle Wash',
    imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    services:SparkleWashServices,
    location: '123 Main Street, Downtown',
    openHours: '8:00 AM - 8:00 PM',
    latitude: -1.2921,
    longitude: 36.8219,
  ),
  CarWash(
    id: '2',
    name: 'CleanRide',
    imageUrl: 'https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=800&q=80',
    services:CleanRide ,
    location: '456 Elm Avenue, Uptown',
    openHours: '7:00 AM - 9:00 PM',
    latitude: -1.2833,	
    longitude: 36.8167
  ),
  CarWash(
    id: '3',
    name: 'Extreme Clean - Ananas Mall',
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    services: ExtremeCleanAnanasMall,
    location: 'Ananas Mall, Kiambu',
    openHours: '7:00 AM - 7:00 PM',
    latitude: -1.1700,
    longitude: 36.8300,
  ),
  CarWash(
    id: '4',
    name: 'Ashworth Car Wash',
    imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=80',
    services: AshworthCarWash,
    location: 'Westlands Road, Nairobi',
    openHours: '7:00 AM - 5:00 PM',
    latitude: -1.2600,
    longitude: 36.7960
  ),
  CarWash(
    id: '5',
    name: 'Auto Sparkle Car Wash',
    imageUrl: 'https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=800&q=80',
    services: AutoSparkleCarWash,
    location: 'Peponi Road opposite Sarit Center, Nairobi',
    openHours: '7:00 AM - 7:00 PM',
    latitude: -1.2540,
    longitude:36.8070 ,
  ),
  CarWash(
    id: '6',
    name: 'The Rok Carwash',
    imageUrl: 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=80',
    services: TheRokCarwash,
    location: '16 School Lane, Nairobi',
    openHours: '8:00 AM - 6:00 PM',
    latitude: -1.2800,
    longitude:36.8200 
  ),
  CarWash(
    id: '7',
    name: 'Wambugu Car Wash Centre',
    imageUrl: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=800&q=80',
    services: WambuguCarWashCentre,
    location: 'Parklands, Nairobi',
    openHours: '7:00 AM - 6:00 PM',
    latitude: -1.2605	,
    longitude: 36.8300
  ),
  CarWash(
    id: '8',
    name: 'The Accacian Car Wash',
    imageUrl: 'https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?auto=format&fit=crop&w=800&q=80',
    services: TheAccacianCarWash,
    location: 'Limuru Road, Ruaka',
    openHours: '7:00 AM - 8:00 PM',
  latitude: -1.2100	,
  longitude: 36.7800,
  ),
  CarWash(
    id: '9',
    name: 'Happy Vantage Car Wash',
    imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    services: HappyVantageCarWash,
    location: 'Ruaka Town',
    openHours: '8:00 AM - 7:00 PM',
    latitude: -1.2100	,
  longitude:36.7800 
  ),
  CarWash(
    id: '10',
    name: 'Safi Car Wash',
    imageUrl: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=800&q=80',
    services: SafiCarWash,
    location: 'Kiambu Town',
    openHours: '7:00 AM - 6:00 PM',
    latitude: -1.1700,
    longitude: 	36.8300
  ),
];

